### ISSUE TITLE
Add/rm signer UI tweak

### ISSUE THREAD

**Issue by Schwartz10** [glifio/safe#106]
When adding/removing a signer and reviewing the transaction, the new required approvals threshold amount gets left aligned which looks a little weird alongside the other information

I think this should be right aligned? 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/12353734/172532482-7b2ebe7e-f1bc-4bd1-af05-10d9083e0341.png">

**Comment by navFooh** [comment]
Yeah I was considering the same thing, but was worried it also looks weird when right-aligning, because the text in the input fields is left-aligned. There is still the question if we consider the padding on the right side though if we right-align.

So the options are:

A: leave as is

B:
![image](https://user-images.githubusercontent.com/394452/172662537-b4b70132-393d-4ad6-b2d8-18867422c022.png)

C:
![image](https://user-images.githubusercontent.com/394452/172662624-2a5171df-2417-4f75-8c44-3b66a337051a.png)

Let me know what you think

**Comment by navFooh** [comment]
Personally I'm leaning towards C

**Comment by Schwartz10** [comment]
Agree with C
